### ISSUE TITLE
util for polite loading images

### ISSUE THREAD

**Issue by mm-paulie** [mediamonks/temple#9]
would be great to have a polite loader for images. something like this:
  async politeLoadImages() {
    var imagesToCheckLoading = Array.from(document.querySelectorAll("[polite]"));

    var loadedImages = imagesToCheckLoading.map(function(queryString) {
      return hasLoaded(queryString);
    });

    Promise.all(loadedImages).then(this.initEvents);

    function hasLoaded(querySelector) {
      return new Promise(function(resolve, reject) {
        var img1 = querySelector;
        img1.src = img1.getAttribute("data-src");

        img1.addEventListener("load", function() {
          // woo yey image loaded
          resolve(this);
        });

        img1.addEventListener("error", function(e) {
          // argh everything's broken
          reject(e);
        });
      });
    }
  }

and in your index you would be defining the images to be politely loades as:
<img data-src="./img/frame3.jpg" polite/>

**Comment by mirkovw** [comment]
@mm-paulie is this still an issue? We have polite loading enabled by default now, havent we

**Comment by mm-paulie** [comment]
we have this, however, it's a util, could be implemented by default
